service:
  name: 'comp-a-service'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

custom:
  webpackIncludeModules: true
  webpack:
    packager: 'yarn'
    packagerOptions: {}

functions:
  hello:
    handler: handler.hello